name: sangu
description: The front end for Sangu tracklist manager.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  collection: ^1.14.12
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  json_annotation: ^3.0.1
  auto_size_text: ^2.1.0
  http: ^0.12.1
  grouped_listview: ^0.0.2
  universal_html: ^1.2.2
  localstorage: ^3.0.2
  shared_preferences: ^0.5.7
  google_fonts: ^1.0.0
  just_audio: ^0.1.10
  implicitly_animated_reorderable_list: ^0.2.2
  url_launcher: ^5.4.10
  sangu_websocket:
    path: sangu_websocket

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.9.0

flutter:
  uses-material-design: true
